apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qggcft9w6-go 
  janus-idp.io/tekton: qggcft9w6-go
  backstage.io/kubernetes-id: qggcft9w6-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qggcft9w6-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml